### PR TITLE
download messages per domain

### PR DESCRIPTION
**Pull request by Gladhon**
currently, if i use the download command, i get all messages in each domain, which is wrong.
With this change it download only messages each domain/tag definied in config

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. You are correct!

**Comment by Gladhon** [comment]
thx for fast reply and merge, when will you release it ?

**Comment by Nyholm** [comment]
Released 0.6.2

**Comment by Nyholm** [comment]
hm. This broke things horribly in my app... This needs to be changed/reverted.

**Pull request merged**
