### PR TITLE
Allow localise.biz 1.0

### PR DESCRIPTION
**Pull request by XWB**

### CODE REVIEW

**Comment by innocenzi** [comment]
This would be great.

**Comment by tompiard** [comment]
This would be great indeed.

**Comment by XWB** [comment]
Ping @Nyholm

**Comment by Nyholm** [comment]
Thank you

**Comment by innocenzi** [comment]
Thanks!

**Comment by XWB** [comment]
@hawezo Would you be able to tag a new minor version? It would be nice to have a stable version with Symfony 4.2 support (https://github.com/php-translation/loco-adapter/commit/a886cc0d146d6dfcd68a9af21e15b1b85a386a99).

**Comment by Nyholm** [comment]
I tagged a new version: https://github.com/php-translation/loco-adapter/releases/tag/0.8.1

**Pull request merged**
