### PR TITLE
Fix the branch alias after 0.4.0 release

### PR DESCRIPTION
**Pull request by damienalexandre**

### CODE REVIEW

**Comment by damienalexandre** [comment]
Also, a release should be done to allow installing this project. At the moment, this composer can't work:

```json
{
    "name": "test/tmp",
    "require": {
        "php-translation/symfony-bundle": "^0.6.1",
        "php-translation/loco-adapter": "^0.4.0"
    }
}
```
But 7683644632ff993809ca51759d6e889c650706e8 fix it.

**Comment by Nyholm** [comment]
Okey, Doing it after dinner

**Comment by Nyholm** [comment]
0.5.0 is released

**Comment by damienalexandre** [comment]
Thanks a lot 🤗

Le 29 janv. 2018 7:44 PM, "Tobias Nyholm" <notifications@github.com> a
écrit :

**Pull request merged**
